### PR TITLE
[niconico] Add content filter and sort filter

### PR DESCRIPTION
**Pull request by 34j**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

This change adds `content filters` (which allows full-text search for tags) and `sorting filters` in niconico.
As of now sorting filters cannot be manipulated from the UI and waiting for TeamNewPipe/NewPipe#8837 to be merged.

### CODE REVIEW

**Comment by InfinityLoop1309** [comment]
Thanks for your contribution! This is a fantastic feature. I will check it once the upstream PR is merged.

**Comment by 34j** [comment]
Just in case my terrible English is misinterpreted, even if the PR above are not merged, (and even if it were merged, some changes would be needed.) the change for `content filters` are still valid and a full-text search capability for tags will be added, and do not cause any errors regarding to `sorting filters`. I included the code for sorting filters because it was after implementing it that I realize that it does not make sense (although there is such a function to override) and it took some effort, but if that is the problem, I will address it immediately.

**Comment by InfinityLoop1309** [comment]
Sorry for late response. I am really busy these days.

That seems good, but there is one thing. "Tags" is a little bit confusing and I think it is better to use "TagsOnly".
Also please ignore my fault of lowercase. It should be "All" and "TagsOnly" instead of all lowercase.

I noticed you have cloned the client. It would be nice if you can merge the upstream PR so that we can have a new feature and make use of (and test) the sorting filters. That PR is stuck now and I don't think it would be finished in ~2 months.

**Comment by 34j** [comment]
Thank you for taking the time to reply.

First, the reason why I set "tags" to `snake_case` is in reference to [YouTubeSearchQueryHandlerFactory](https://github.com/InfinityLoop1309/NewPipeExtractor/blob/main/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeSearchQueryHandlerFactory.java). They will be translated in NewPipeExtractor's strings.xml and shown capitalized if the locale is English. However, if it is too much trouble to add them, I think there is a lazy implementation that capitalizes "tags". (And that is why I went uppercase in the first place.) If you have already thought this far, sorry.

The reason I forked the client was to implement another feature (I will open a issue or a PR later.), and I am not willing to rush into merging unfinished code right now.

**Comment by InfinityLoop1309** [comment]
That's OK. Working on it.

**Comment by InfinityLoop1309** [comment]
Migrate to #20

**Pull request closed without merging**
